[build]
  publish = "public"
  command = "pip install -r requirements.txt && pip install -r public/requirements.txt && gunicorn --workers=3 --timeout 120 --chdir public main:app"
  functions = "functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
