[build]
  publish = "public"
  command = "pip install -r public/requirements.txt && python public/main.py"
  functions = "functions"

[[redirects]]
  from = "/*"
  to: "public/index.html"
  status = 200
