[build]
  publish = "public"
  command = "python public/main.py"
  functions = "functions"  # Questo indica a Netlify dove trovare le funzioni serverless

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
