[build]
  publish = "public"
  command = "pip install -r public/requirements.txt && gunicorn --chdir public main:app"
  functions = "functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
